# collections/requirements.yml
---
collections:
  - name: community.hashi_vault
    version: ">=7.0.0"
  - name: community.okd
    version: ">=5.0.0"
  - name: kubernetes.core
    version: ">=6.0.0"
  - name: community.crypto
    version: ">=2.16.0"
  - name: ansible.controller
    version: ">=4.7.0"
