---
- name: Test Vault secret read
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vault_addr: "{{ lookup('env','VAULT_ADDR') }}"
    vault_token: "{{ lookup('env','VAULT_TOKEN') }}"
    vault_namespace: "admin"
    vault_mount: "openshift"
    cluster_id: "{{ lookup('env','CLUSTER_ID') }}"

  tasks:
    - name: Read secret from HCP Vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        namespace: "{{ vault_namespace }}"
        engine_mount_point: "{{ vault_mount }}"
        path: "rosa/{{ cluster_id }}"
      register: rosa_secret

    - name: Show secret
      debug:
        var: rosa_secret.data
