apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: db-creds-rds-admin
  namespace: app-2
spec:
  vaultAuthRef: vault-auth
  mount: rosa-2lit29efhda2oils244c820lep0sgg5m-database
  path: creds/rds-admin
  allowStaticCreds: true
  destination:
    create: true
    name: db-creds-rds-admin
  refreshAfter: 5m
