---
- name: Bootstrap Ansible Automation Platform (AAP) with Projects, Inventory, and Job Templates
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller

  vars:
    cluster_id: ""
    controller_host: ""
    controller_username: "admin"
    controller_password: "ansible123!"
    controller_validate_certs: false
    vault_addr: ""
    vault_namespace: "admin/rosa-{{cluster_id}}"
    vault_role_id: ""
    vault_secret_id: ""
    organization: "Default"

  tasks:
    - name: Create Vault AppRole credential (built-in HashiCorp Vault Secret Lookup)
      ansible.controller.credential:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        name: "Vault AppRole Credential"
        description: "AppRole authentication for connecting AAP to Vault via env vars"
        organization: "{{ organization }}"
        credential_type: "HashiCorp Vault Secret Lookup"
        inputs:
          url: "{{ vault_addr }}"
          namespace: "{{ vault_namespace }}"
          default_auth_path: "approle-aap-{{cluster_id}}"
          role_id: "{{ vault_role_id }}"
          secret_id: "{{ vault_secret_id }}"
          api_version: "v2"
        state: present

    - name: Create custom credential type for OpenShift API
      ansible.controller.credential_type:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        name: "OpenShift API Credential"
        description: "Holds OCP API credentials pulled dynamically from Vault"
        kind: cloud
        inputs:
          fields:
            - id: api_url
              type: string
              label: OCP API URL
              secret: true
            - id: ocp_username
              type: string
              label: OCP Username
              secret: true
            - id: ocp_password
              type: string
              label: OCP Password
              secret: true
          required:
            - api_url
            - ocp_username
            - ocp_password
        injectors:
          extra_vars:
            api_url: !unsafe "{{ api_url }}"
            ocp_username: !unsafe "{{ ocp_username }}"
            ocp_password: !unsafe "{{ ocp_password }}"
        state: present

    - name: Create OpenShift API Credential (empty)
      ansible.controller.credential:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        name: "OpenShift Infra Credential"
        description: "OCP API creds populated from Vault KV"
        organization: "{{ organization }}"
        credential_type: "OpenShift API Credential"
        state: present

    - name: Link api_url field to Vault KV (input source)
      ansible.controller.credential_input_source:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        target_credential: "OpenShift Infra Credential"
        input_field_name: "api_url"
        source_credential: "Vault AppRole Credential"         # the external credential you created earlier
        metadata:
          secret_path: "openshift-rosa-{{ cluster_id }}/infra"                                               # path under the mount
          secret_key: "api_url"                                              # key in KV
          # auth_path: "approle-aap"     # optional override (uses default_auth_path from source cred)
          # secret_version: 0            # optional for KV v2
        state: present

    - name: Link ocp_username field to Vault KV (input source)
      ansible.controller.credential_input_source:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        target_credential: "OpenShift Infra Credential"
        input_field_name: "ocp_username"
        source_credential: "Vault AppRole Credential"
        metadata:
          secret_path: "openshift-rosa-{{ cluster_id }}/infra"
          secret_key: "username"
        state: present

    - name: Link ocp_password field to Vault KV (input source)
      ansible.controller.credential_input_source:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        target_credential: "OpenShift Infra Credential"
        input_field_name: "ocp_password"
        source_credential: "Vault AppRole Credential"
        metadata:
          secret_path: "openshift-rosa-{{ cluster_id }}/infra"
          secret_key: "password"
        state: present

    - name: Attach credential on Job Templates
      ansible.controller.job_template:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        name: "{{ item }}"
        organization: "{{ organization }}"
        state: present
        credentials:
          - "OpenShift Infra Credential"
      loop:
        - "OCP - TF Admin SA Setup"
        - "OCP - VSO Operator Install"


