---
- name: Bootstrap Ansible Automation Platform (AAP) with Projects, Inventory, and Job Templates
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - ansible.controller

  vars:
    controller_host: ""
    controller_username: "admin"
    controller_password: "ansible123!"
    controller_validate_certs: false
    vault_addr: ""
    vault_namespace: "admin"
    vault_role_id: ""
    vault_secret_id: ""
    organization: "Default"

  tasks:
    - name: Create Vault AppRole credential (built-in HashiCorp Vault Secret Lookup)
      ansible.controller.credential:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        name: "Vault AppRole Credential"
        description: "AppRole authentication for connecting AAP to Vault via env vars"
        organization: "{{ organization }}"
        credential_type: "HashiCorp Vault Secret Lookup"
        inputs:
          url: "{{ vault_addr }}"
          namespace: "{{ vault_namespace }}"
          default_auth_path: "approle-aap"
          role_id: "{{ vault_role_id }}"
          secret_id: "{{ vault_secret_id }}"
          api_version: "v2"
        state: present
        
    - name: Create custom credential type for OpenShift API
      ansible.controller.credential_type:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        name: "OpenShift API Credential"
        description: "Holds OCP API credentials pulled dynamically from Vault"
        kind: cloud
        inputs:
          fields:
            - id: api_url
              type: string
              label: OCP API URL
              secret: true
            - id: ocp_username
              type: string
              label: OCP Username
              secret: true
            - id: ocp_password
              type: string
              label: OCP Password
              secret: true
        injectors:
          extra_vars:
            api_url: '{{ api_url }}'
            ocp_username: '{{ ocp_username }}'
            ocp_password: '{{ ocp_password }}'
        state: present

