apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "guestbook.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "guestbook.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
