{{- if .Values.vault.staticSecrets }}
{{- range .Values.vault.staticSecrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: {{ $.Values.vault.authRef }}
  mount: {{ .mount }}
  path: {{ .path }}
  type: {{ .type | default "kv-v2" }}
  destination:
    create: true
    name: {{ .destination.name }}
    {{- if .destination.type }}
    type: {{ .destination.type }}
    {{- end }}
  {{- if .refreshAfter }}
  refreshAfter: {{ .refreshAfter }}
  {{- end }}
---
{{- end }}
{{- end }}
