{{- if .Values.vault.dynamicSecrets }}
{{- range .Values.vault.dynamicSecrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: {{ $.Values.vault.authRef }}
  mount: {{ .mount }}
  path: {{ .path }}
  {{- if .allowStaticCreds }}
  allowStaticCreds: {{ .allowStaticCreds }}
  {{- end }}
  destination:
    create: true
    name: {{ .destination.name }}
    {{- if .destination.type }}
    type: {{ .destination.type }}
    {{- end }}
  {{- if .refreshAfter }}
  refreshAfter: {{ .refreshAfter }}
  {{- end }}
  {{- if .renewalPercent }}
  renewalPercent: {{ .renewalPercent }}
  {{- end }}
---
{{- end }}
{{- end }}
